### ISSUE TITLE
Add your name!

### ISSUE THREAD

**Issue by glaukiol1** [glaukiol1/easy-contributions-for-first-time#1]
Ready to make your first contribution? Goto the README.md file to learn how!

**Comment by theprogrammedwords** [comment]
Can I take this up? Thanks.

**Comment by theprogrammedwords** [comment]
@glaukiol1

**Comment by glaukiol1** [comment]
Yes of course!

**Comment by glaukiol1** [comment]
Im helping people getting their first contributions
